name: Deploy to staging
on:
  push:
    branches:
      - "master"

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ${{ github.repository }}
      image_tag: latest
      dockerfile: ./Dockerfile