name: Build stage/test
on:
  push:
    branches:
      - "master"

jobs:
  build:
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ${{ github.repository }}
      dockerfile: ./Dockerfile